version: "3.7"
services:
  postgres:
    image: postgres:15.4-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: crm
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "3002:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5173:5173"

volumes:
  postgres-volume:
    driver: local
