version: "3.7"
services:
  postgres:
    image: postgres:15.4-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: crm
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  backend:
    image: cheblan/crm-backend:latest
    container_name: backend
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgres
    volumes:
      - uploads-volume:/uploads

  frontend:
    image: cheblan/crm-frontend:latest
    container_name: frontend
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5173:5173"

volumes:
  postgres-volume:
    driver: local
  uploads-volume:
    driver: local
